### ISSUE TITLE
Geometry features missing from output shapefile

### ISSUE THREAD

**Issue by Douglas-K** [linz/lds_topo_reblocker#11]
Some railway features are not being copied into the output shapefile.  I have just realised this error has been happening in the last few releases.  It was working in October 2016, then the errors started appearing in January 2017.  The LayerReader.py I am using was updated November 2016 and made Python3 compatible.  I will check for errors in other layers.

**Comment by ghost** [comment]
@Douglas-K it looks like something changed in the data around 31/3 last year. The rail section was suddenly merged into one piece and now its back into 5 separate parts again

```
"2015-04-23 17:15:00";"new_railway_cl";100024382;"{2462720,2462736,2462790,5940248}"
"2015-04-23 17:15:00";"new_railway_cl";100024382;"{2462720,2462736,2462790,5940248}"
"2015-06-03 17:49:00";"new_railway_cl";100024382;"{2462720,2462736,2462790,5940248}"
"2015-08-07 10:13:00";"new_railway_cl";100076969;"{2462788,2462720,2462736,2462790,2462840,5940248}"
"2015-08-10 15:41:00";"new_railway_cl";100076969;"{2462788,2462720,2462736,2462790,2462840,5940248}"
"2015-08-20 16:11:00";"new_railway_cl";100076969;"{2462788,2462720,2462736,2462790,2462840,5940248}"
"2015-10-27 08:26:00";"new_railway_cl";100076969;"{2462788,2462720,2462736,2462790,2462840,5940248}"
"2015-11-11 13:42:00";"new_railway_cl";100076969;"{2462788,2462720,2462736,2462790,2462840,5940248}"
"2015-12-22 17:36:00";"new_railway_cl";100076969;"{2462788,2462720,2462736,2462790,2462840,5940248}"
"2016-03-31 11:10:00";"new_railway_cl";100089071;"{2462790,5940248}"
"2016-06-01 17:46:00";"new_railway_cl";100089071;"{2462790,5940248}"
"2016-08-24 13:31:00";"new_railway_cl";100089071;"{2462790,5940248}"
"2016-10-18 14:06:00";"new_railway_cl";100089071;"{2462790,5940248}"
```

**Comment by ghost** [comment]
Error caused when:
1) NS boundary join succeeds creating new segment, temp ufid assigned
a|b|c|d ---> a|e|d
2) EW boundary join either side of new segment fails (st_linemerge misaligned)
a|e|d --x-> a||d, e
3) new segment orphaned and temp id removed
a||d ---> a,d
4) new segment lost

**Comment by ghost** [comment]
Analysing the problem linestrings, @Douglas-K has discovered that this issue occurs when loops appear (intentional or not) in one or more of the component lines. This agrees with the observation that st_linemerge(st_collect(...)) produces a correctly joined linestring whereas st_linemerge(st_union(...)) produces a segmented multilinestring that fails as a reblocked feature.

For this upcoming topo release the source features will be modified/fixed removing loops. This will remedy the current issue but doesn't resolve the bug where 'un-join-able' linestrings get lost in the reblock process.

**Comment by ghost** [comment]
New PR https://github.com/linz/lds_topo_reblocker/pull/12 addresses this issue. Testing shows that st_collect replacing st_union fixes the issue of excluded linestrings but the error log highlights other possibly unreleted or previously seen join failures. The impact of this change will need to be evaluated in production
