### ISSUE TITLE
Reblocker deployment improvements

### ISSUE THREAD

**Issue by ghost** [linz/lds_topo_reblocker#4]
Adapting reblocker so it is able to be deployed using ansible deployment template

**Comment by ghost** [comment]
Customisation of vagrant environment with scoped web/db and client boxes

**Comment by ghost** [comment]
1. update vagrant to 1.9.3 to avoid ifupdown fail causing halt on ssh
2. modify ansible.version.minor >= 0 since ansible version 2.0.0.2 fails
3. change system_network_device = enp0s3 instead of eth1 in Vagrantfile and basic/defaults/main
4. eliminate httplib2>=0.7 error by upgrading ansible to 2.2.0

**Comment by ghost** [comment]
5. "apt:  update_cache: yes" fails, change to "shell: apt update"

**Comment by ghost** [comment]
6. ansible fails to recognise localhost/127... proxies, must use "environment: http_proxy: http://aaa.bbb.ccc.ddd:3128". Discovered this was because proxy defined as localhost not portable to virtual env so startup script needed to define from ifconfig

**Comment by imincik** [comment]
@jrlinz , please submit pull request to Ansible Deployment for every fix you will do. Thanks

**Comment by ghost** [comment]
Wrote a quick workaround but accidentally pushed it straight into master. I'll pull it out again if you want

**Comment by imincik** [comment]
> Wrote a quick workaround but accidentally pushed it straight into master. I'll pull it out again if you want

I reverted that change. Next time it is really better to have PR and review for such non-trivial change.

**Comment by imincik** [comment]
I think, we should open issue in ansible-deployment and discuss proper cntlm implementation.

**Comment by imincik** [comment]
@jrlinz , Reblocker repository can't contain it's own copy of whole Ansible deployment. It can just add Reblocker specific roles on top of general ones (basic and db). See docs [1] and have a look to Gazetteer as an example [2] how to reuse Ansible roles.

1 - https://github.com/linz/ansible-deployment/blob/master/README.md#reused-deployment-in-other-projects
2 - https://github.com/linz/gazetteer/tree/1-deployment

**Comment by ghost** [comment]
@imincik I was just using it as a template. I have no intention of keeping most of that stuff esp the BDE installation. Also, that's why I was originally using 16.04. No need to be compatible

**Comment by imincik** [comment]
> @imincik I was just using it as a template. I have no intention of keeping most of that stuff esp the BDE installation. Also, that's why I was originally using 16.04. No need to be compatible

It is very bad idea. Maybe the worse idea I can imagine. It is the same as you fork some library to your project. Then you are on your own with its maintenance and development. "ansible-deployment" is such library for deployment.

For 16.04 we should implement proper support for "ansible-deployment".

I will separate BDE Processor from "ansible-deployment". It shouldn't be there. Issue created (https://github.com/linz/ansible-deployment/issues/70)

**Comment by imincik** [comment]
Also it looks like you have "BDE Processor" deployment in "master/deployment/roles/webserver"

**Comment by ghost** [comment]
Alright. So I'll just remove it then.
